apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbs.dbaas.k8s.ibm.com
spec:
  group: dbaas.k8s.ibm.com
  names:
    kind: MongoDB
    listKind: MongoDBList
    plural: mongodbs
    singular: mongodb
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
